server.port=${PORT:8080}
spring.application.name=aluguel-temporada-api
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
jwt.secret=665ed9f9c65dfcb67e3e17f1d6b7e3b9533668e2cb510a4f40411f41dc74edc1
